//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesTest.DAL.i18n {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServicesTest.DAL.i18n.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update tool.
        /// </summary>
        public static string ActualizarHerramientaForm {
            get {
                return ResourceManager.GetString("ActualizarHerramientaForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update tool.
        /// </summary>
        public static string actualizarHerramientaToolStripMenuItem {
            get {
                return ResourceManager.GetString("actualizarHerramientaToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update User.
        /// </summary>
        public static string ActualizarUsuarioForm {
            get {
                return ResourceManager.GetString("ActualizarUsuarioForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        public static string ayudaToolStripMenuItem {
            get {
                return ResourceManager.GetString("ayudaToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Backup.
        /// </summary>
        public static string BackupForm {
            get {
                return ResourceManager.GetString("BackupForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Backup.
        /// </summary>
        public static string BackupToolStripMenuItem {
            get {
                return ResourceManager.GetString("BackupToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Binnacle.
        /// </summary>
        public static string BitacoraToolStripMenuItem {
            get {
                return ResourceManager.GetString("BitacoraToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        public static string btnAceptar {
            get {
                return ResourceManager.GetString("btnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        public static string btnActualizar {
            get {
                return ResourceManager.GetString("btnActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string btnAgregar {
            get {
                return ResourceManager.GetString("btnAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string btnBuscar {
            get {
                return ResourceManager.GetString("btnBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculate.
        /// </summary>
        public static string btnCalcular {
            get {
                return ResourceManager.GetString("btnCalcular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string btnCancelar {
            get {
                return ResourceManager.GetString("btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        public static string btnConfirmar {
            get {
                return ResourceManager.GetString("btnConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter.
        /// </summary>
        public static string btnFiltrar {
            get {
                return ResourceManager.GetString("btnFiltrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string btnGuardar {
            get {
                return ResourceManager.GetString("btnGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Print or export.
        /// </summary>
        public static string btnImprimir {
            get {
                return ResourceManager.GetString("btnImprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string btnNuevoUsuario {
            get {
                return ResourceManager.GetString("btnNuevoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restore.
        /// </summary>
        public static string btnRestaurar {
            get {
                return ResourceManager.GetString("btnRestaurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculate losses.
        /// </summary>
        public static string CalcularPerdidasForm {
            get {
                return ResourceManager.GetString("CalcularPerdidasForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculate losses.
        /// </summary>
        public static string CalcularPerdidasToolStripMenuItem {
            get {
                return ResourceManager.GetString("CalcularPerdidasToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculate budget.
        /// </summary>
        public static string CalcularPresupuestoForm {
            get {
                return ResourceManager.GetString("CalcularPresupuestoForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculate.
        /// </summary>
        public static string calcularToolStripMenuItem {
            get {
                return ResourceManager.GetString("calcularToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catalog.
        /// </summary>
        public static string CatalogoForm {
            get {
                return ResourceManager.GetString("CatalogoForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enabled.
        /// </summary>
        public static string checkBoxHabilitado {
            get {
                return ResourceManager.GetString("checkBoxHabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Binnacle.
        /// </summary>
        public static string FormBitacora {
            get {
                return ResourceManager.GetString("FormBitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tools.
        /// </summary>
        public static string herramientasToolStripMenuItem {
            get {
                return ResourceManager.GetString("herramientasToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Init.
        /// </summary>
        public static string InicioForm {
            get {
                return ResourceManager.GetString("InicioForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string InicioSesionForm {
            get {
                return ResourceManager.GetString("InicioSesionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity.
        /// </summary>
        public static string labelCantidad {
            get {
                return ResourceManager.GetString("labelCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity (Kg).
        /// </summary>
        public static string labelCantidadKG {
            get {
                return ResourceManager.GetString("labelCantidadKG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comment.
        /// </summary>
        public static string labelComentario {
            get {
                return ResourceManager.GetString("labelComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Discount.
        /// </summary>
        public static string labelDescuento {
            get {
                return ResourceManager.GetString("labelDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brand.
        /// </summary>
        public static string labelMarca {
            get {
                return ResourceManager.GetString("labelMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string labelNombre {
            get {
                return ResourceManager.GetString("labelNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products.
        /// </summary>
        public static string labelProducto {
            get {
                return ResourceManager.GetString("labelProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose the products.
        /// </summary>
        public static string labelProductosPresupuesto {
            get {
                return ResourceManager.GetString("labelProductosPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provider.
        /// </summary>
        public static string labelProveedor {
            get {
                return ResourceManager.GetString("labelProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose the tools necessary to make the product.
        /// </summary>
        public static string labelStockHerramientas {
            get {
                return ResourceManager.GetString("labelStockHerramientas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose the raw material necessary to make the product.
        /// </summary>
        public static string labelStockMateriaPrima {
            get {
                return ResourceManager.GetString("labelStockMateriaPrima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Due date.
        /// </summary>
        public static string labelVencimiento {
            get {
                return ResourceManager.GetString("labelVencimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name.
        /// </summary>
        public static string lblApellido {
            get {
                return ResourceManager.GetString("lblApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User code.
        /// </summary>
        public static string lblCodUsuario {
            get {
                return ResourceManager.GetString("lblCodUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Level.
        /// </summary>
        public static string lblCriticidad {
            get {
                return ResourceManager.GetString("lblCriticidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Since.
        /// </summary>
        public static string lblDesde {
            get {
                return ResourceManager.GetString("lblDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        public static string lblDireccion {
            get {
                return ResourceManager.GetString("lblDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To.
        /// </summary>
        public static string lblHasta {
            get {
                return ResourceManager.GetString("lblHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string lblIdioma {
            get {
                return ResourceManager.GetString("lblIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat password.
        /// </summary>
        public static string lblPassword2 {
            get {
                return ResourceManager.GetString("lblPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actual role.
        /// </summary>
        public static string lblRolActual {
            get {
                return ResourceManager.GetString("lblRolActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Role.
        /// </summary>
        public static string lblRoles {
            get {
                return ResourceManager.GetString("lblRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        public static string lblTelefono {
            get {
                return ResourceManager.GetString("lblTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string lblUsuario {
            get {
                return ResourceManager.GetString("lblUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        public static string lblWelcome {
            get {
                return ResourceManager.GetString("lblWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List.
        /// </summary>
        public static string listarHerramientasToolStripMenuItem {
            get {
                return ResourceManager.GetString("listarHerramientasToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Raw material.
        /// </summary>
        public static string ListarMateriaPrimaForm {
            get {
                return ResourceManager.GetString("ListarMateriaPrimaForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promotions.
        /// </summary>
        public static string ListarPromocionesForm {
            get {
                return ResourceManager.GetString("ListarPromocionesForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        public static string ListarUsuariosForm {
            get {
                return ResourceManager.GetString("ListarUsuariosForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Raw material.
        /// </summary>
        public static string MateriaPrimaToolStripMenuItem {
            get {
                return ResourceManager.GetString("MateriaPrimaToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update raw material.
        /// </summary>
        public static string MenuItemActualizarMateriaPrima {
            get {
                return ResourceManager.GetString("MenuItemActualizarMateriaPrima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update product.
        /// </summary>
        public static string MenuItemActualizarProducto {
            get {
                return ResourceManager.GetString("MenuItemActualizarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update promotion.
        /// </summary>
        public static string MenuItemActualizarPromocion {
            get {
                return ResourceManager.GetString("MenuItemActualizarPromocion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update User.
        /// </summary>
        public static string MenuItemActualizarUsuario {
            get {
                return ResourceManager.GetString("MenuItemActualizarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculate Budget.
        /// </summary>
        public static string MenuItemCalcularPresupuesto {
            get {
                return ResourceManager.GetString("MenuItemCalcularPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catalog.
        /// </summary>
        public static string MenuItemCatalogo {
            get {
                return ResourceManager.GetString("MenuItemCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        public static string MenuItemNuevaPromocion {
            get {
                return ResourceManager.GetString("MenuItemNuevaPromocion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        public static string MenuItemNuevoMateriaPrima {
            get {
                return ResourceManager.GetString("MenuItemNuevoMateriaPrima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        public static string MenuItemNuevoProducto {
            get {
                return ResourceManager.GetString("MenuItemNuevoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New User.
        /// </summary>
        public static string MenuItemNuevoUsuario {
            get {
                return ResourceManager.GetString("MenuItemNuevoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sale report.
        /// </summary>
        public static string MenuItemReportesVentas {
            get {
                return ResourceManager.GetString("MenuItemReportesVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List.
        /// </summary>
        public static string MenuItemVerMateriaPrima {
            get {
                return ResourceManager.GetString("MenuItemVerMateriaPrima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List.
        /// </summary>
        public static string MenuItemVerPromociones {
            get {
                return ResourceManager.GetString("MenuItemVerPromociones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users list.
        /// </summary>
        public static string MenuItemVerUsuarios {
            get {
                return ResourceManager.GetString("MenuItemVerUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want restore the backup selected?.
        /// </summary>
        public static string msgConfirm {
            get {
                return ResourceManager.GetString("msgConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error in the backup restore. Call administrator system..
        /// </summary>
        public static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid lastname.
        /// </summary>
        public static string MsgErrorApellido {
            get {
                return ResourceManager.GetString("MsgErrorApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must complete all the required fields.
        /// </summary>
        public static string MsgErrorCamposObligatorios {
            get {
                return ResourceManager.GetString("MsgErrorCamposObligatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid quantity.
        /// </summary>
        public static string MsgErrorCantidad {
            get {
                return ResourceManager.GetString("MsgErrorCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter username and password to log into the system.
        /// </summary>
        public static string MsgErrorCompletarLogin {
            get {
                return ResourceManager.GetString("MsgErrorCompletarLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid address.
        /// </summary>
        public static string MsgErrorDireccion {
            get {
                return ResourceManager.GetString("MsgErrorDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid email.
        /// </summary>
        public static string MsgErrorEmail {
            get {
                return ResourceManager.GetString("MsgErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integrity error in the database. Contact your system administrator..
        /// </summary>
        public static string MsgErrorIntegridad {
            get {
                return ResourceManager.GetString("MsgErrorIntegridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect user or password .
        /// </summary>
        public static string MsgErrorLogin {
            get {
                return ResourceManager.GetString("MsgErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid brand.
        /// </summary>
        public static string MsgErrorMarca {
            get {
                return ResourceManager.GetString("MsgErrorMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error registering raw material.
        /// </summary>
        public static string MsgErrorMPRegister {
            get {
                return ResourceManager.GetString("MsgErrorMPRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid name.
        /// </summary>
        public static string MsgErrorNombre {
            get {
                return ResourceManager.GetString("MsgErrorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match.
        /// </summary>
        public static string MsgErrorPassword {
            get {
                return ResourceManager.GetString("MsgErrorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Provider.
        /// </summary>
        public static string MsgErrorProveedor {
            get {
                return ResourceManager.GetString("MsgErrorProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Phone.
        /// </summary>
        public static string MsgErrorTelefono {
            get {
                return ResourceManager.GetString("MsgErrorTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid user code.
        /// </summary>
        public static string MsgErrorUser {
            get {
                return ResourceManager.GetString("MsgErrorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user could not updated.
        /// </summary>
        public static string MsgErrorUserActualizar {
            get {
                return ResourceManager.GetString("MsgErrorUserActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User code  already exists.
        /// </summary>
        public static string MsgErrorUserExiste {
            get {
                return ResourceManager.GetString("MsgErrorUserExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user could not register.
        /// </summary>
        public static string MsgErrorUserRegister {
            get {
                return ResourceManager.GetString("MsgErrorUserRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restore completed successfully.
        /// </summary>
        public static string msgOk {
            get {
                return ResourceManager.GetString("msgOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Raw Material successfully registered.
        /// </summary>
        public static string MsgOkMPRegister {
            get {
                return ResourceManager.GetString("MsgOkMPRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successfully updated user.
        /// </summary>
        public static string MsgOkUserActualizar {
            get {
                return ResourceManager.GetString("MsgOkUserActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successfully registered user.
        /// </summary>
        public static string MsgOkUserRegister {
            get {
                return ResourceManager.GetString("MsgOkUserRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New tool.
        /// </summary>
        public static string NuevaHerramientaForm {
            get {
                return ResourceManager.GetString("NuevaHerramientaForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        public static string nuevaHerramientaToolStripMenuItem {
            get {
                return ResourceManager.GetString("nuevaHerramientaToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New promotion.
        /// </summary>
        public static string NuevaPromocionForm {
            get {
                return ResourceManager.GetString("NuevaPromocionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New sale.
        /// </summary>
        public static string NuevaVentaForm {
            get {
                return ResourceManager.GetString("NuevaVentaForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        public static string nuevaVentaToolStripMenuItem {
            get {
                return ResourceManager.GetString("nuevaVentaToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New raw material.
        /// </summary>
        public static string NuevoMateriaPrimaForm {
            get {
                return ResourceManager.GetString("NuevoMateriaPrimaForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Product.
        /// </summary>
        public static string NuevoProductoForm {
            get {
                return ResourceManager.GetString("NuevoProductoForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products.
        /// </summary>
        public static string productosToolStripMenuItem {
            get {
                return ResourceManager.GetString("productosToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promotions.
        /// </summary>
        public static string promocionesToolStripMenuItem {
            get {
                return ResourceManager.GetString("promocionesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reports.
        /// </summary>
        public static string reportesToolStripMenuItem {
            get {
                return ResourceManager.GetString("reportesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Security.
        /// </summary>
        public static string SeguridadToolStripMenuItem {
            get {
                return ResourceManager.GetString("SeguridadToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restore.
        /// </summary>
        public static string titleConfirm {
            get {
                return ResourceManager.GetString("titleConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tracking.
        /// </summary>
        public static string TrackingForm {
            get {
                return ResourceManager.GetString("TrackingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tracking DataBase.
        /// </summary>
        public static string TrackingToolStripMenuItem {
            get {
                return ResourceManager.GetString("TrackingToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Management.
        /// </summary>
        public static string UsuariosForm {
            get {
                return ResourceManager.GetString("UsuariosForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        public static string UsuariosToolStripMenuItem {
            get {
                return ResourceManager.GetString("UsuariosToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sales.
        /// </summary>
        public static string ventasToolStripMenuItem {
            get {
                return ResourceManager.GetString("ventasToolStripMenuItem", resourceCulture);
            }
        }
    }
}
