USE [master]
GO

/****** Object:  Database [TC]    Script Date: 19/09/2020 1:43:23 ******/
CREATE DATABASE [TC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TC', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.EQUIPO\MSSQL\DATA\TC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TC_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.EQUIPO\MSSQL\DATA\TC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TC] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TC] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TC] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TC] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TC] SET ARITHABORT OFF 
GO

ALTER DATABASE [TC] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TC] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TC] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TC] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TC] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TC] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TC] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TC] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TC] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TC] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TC] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TC] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TC] SET RECOVERY FULL 
GO

ALTER DATABASE [TC] SET  MULTI_USER 
GO

ALTER DATABASE [TC] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TC] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TC] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TC] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TC] SET  READ_WRITE 
GO

