USE [master]
GO

/****** Object:  Database [TCSecurity]    Script Date: 13/11/2020 2:16:00 ******/
CREATE DATABASE [TCSecurity]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TCSecurity', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.EQUIPO\MSSQL\DATA\TCSecurity.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TCSecurity_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.EQUIPO\MSSQL\DATA\TCSecurity_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TCSecurity].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TCSecurity] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TCSecurity] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TCSecurity] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TCSecurity] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TCSecurity] SET ARITHABORT OFF 
GO

ALTER DATABASE [TCSecurity] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TCSecurity] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TCSecurity] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TCSecurity] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TCSecurity] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TCSecurity] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TCSecurity] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TCSecurity] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TCSecurity] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TCSecurity] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TCSecurity] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TCSecurity] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TCSecurity] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TCSecurity] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TCSecurity] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TCSecurity] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TCSecurity] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TCSecurity] SET RECOVERY FULL 
GO

ALTER DATABASE [TCSecurity] SET  MULTI_USER 
GO

ALTER DATABASE [TCSecurity] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TCSecurity] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TCSecurity] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TCSecurity] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TCSecurity] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TCSecurity] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TCSecurity] SET  READ_WRITE 
GO



